// <auto-generated />
using System;
using Chronos.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chronos.Infrastructure.Persistence.Migrations.Sqlite
{
    [DbContext(typeof(SqliteChronosDbContext))]
    partial class SqliteChronosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Chronos.Domain.Leave.LeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ApproverId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "RequesterId", "Status");

                    b.ToTable("LeaveRequests", (string)null);
                });

            modelBuilder.Entity("Chronos.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("Chronos.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique();

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Chronos.Domain.Users.PasswordHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("PasswordHistories", (string)null);
                });

            modelBuilder.Entity("Chronos.Domain.Users.Right", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Rights", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            Code = "leave.view-own",
                            Description = "View the caller's own leave requests."
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            Code = "leave.request",
                            Description = "Submit a new leave request."
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            Code = "leave.approve",
                            Description = "Approve or reject a leave request."
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            Code = "projects.manage",
                            Description = "Create and manage projects."
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            Code = "users.manage",
                            Description = "Promote/demote users within the organization."
                        });
                });

            modelBuilder.Entity("Chronos.Domain.Users.RoleRight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RightId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Role", "RightId")
                        .IsUnique();

                    b.ToTable("RoleRights", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111101"),
                            RightId = new Guid("11111111-1111-1111-1111-111111111101"),
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111102"),
                            RightId = new Guid("11111111-1111-1111-1111-111111111102"),
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111103"),
                            RightId = new Guid("11111111-1111-1111-1111-111111111101"),
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111104"),
                            RightId = new Guid("11111111-1111-1111-1111-111111111102"),
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111105"),
                            RightId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111106"),
                            RightId = new Guid("11111111-1111-1111-1111-111111111101"),
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111107"),
                            RightId = new Guid("11111111-1111-1111-1111-111111111102"),
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111108"),
                            RightId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111109"),
                            RightId = new Guid("11111111-1111-1111-1111-111111111104"),
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111110"),
                            RightId = new Guid("11111111-1111-1111-1111-111111111105"),
                            Role = 2
                        });
                });

            modelBuilder.Entity("Chronos.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Chronos.Domain.Projects.Project", b =>
                {
                    b.OwnsMany("Chronos.Domain.Projects.GanttTask", "Tasks", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly>("EndDate")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<Guid?>("ParentTaskId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("ProgressPercent")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("ProjectId");

                            b1.ToTable("GanttTasks", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");

                            b1.OwnsMany("Chronos.Domain.Projects.TaskDependency", "Dependencies", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("GanttTaskId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("LagDays")
                                        .HasColumnType("INTEGER");

                                    b2.Property<Guid>("PredecessorTaskId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Type")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("Id");

                                    b2.HasIndex("GanttTaskId");

                                    b2.ToTable("GanttTaskDependencies", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("GanttTaskId");
                                });

                            b1.Navigation("Dependencies");
                        });

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
